
module.exports = {
    encode: require('./encode'),
    streamToBuffer: require('./streamToBuffer'),
    decode: require('./decode'),
    hashPassword: require('./hashPassword'),
    compareHash: require('./compareHash'),
    contains: require('./contains'),
    getStandardMobile: require('./getStandardMobile'),
    generatePassword: require('./generatePassword'),
    isPersianStr: require('./isPersianStr'),
    isPhone : require('./isPhone'),
    isPersianText: require('./isPersianText'),
    isIrNationalId: require('./isIrNationalId'),
    isJalaiDate: require('./isJalaliDate'),
    isFullJalaliDate: require('./isFullJalaliDate'),
    fullGregorianToFullJalali: require('./fullGregorianToFullJalali'),
    getFullJalaliStandard: require('./getFullJalaliStandard'),
    getFullGregorianStandard: require('./getFullGregorianStandard'),
    getCurrentDate: require('./getCurrentDate'),
    fullJelaliToFullGregorian: require('./fullJalaliToFullGregorian'),
    isBefore: require('./isBefore'),
    isAfter: require('./isAfter'),
    isSame: require('./isSame'),
    isString: require('./isString'),
    isSameOrBefore: require('./isSameOrBefore'),
    isSameOrAfter: require('./isSameOrAfter'),
    isBetween: require('./isBetween'),
    isTime: require('./isTime'),
    isJson: require('./isJson'),
    isJWT: require('./isJWT'),
    isEmail: require('./isEmail'),
    isUrl: require('./isUrl'),
    isEmpty: require('./isEmpty'),
    isBoolean: require('./isBoolean'),
    seriousError: require('./seriousError'),
    secondsToTime: require('./durationToFormat'),
    dateToTimestamp: require('./dateToTimestamp'),
    durationToFormat: require('./durationToFormat'),
    timestampToformat: require('./timestampToformat'),
    timestampToformat2: require('./timestampToformat2'),
    timeConvertFormat: require('./timeConvertFormat'),
    timeToseconds: require('./timeToseconds'),
    formatErrors: require('./formatErrors'),
    throwError: require('./throwError'),
    isValidTime: require('./isValidTime'),
  };